# Generated by Django 6.0.5 on 2026-05-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='blurb',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
