services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - recipe-app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy
    networks:
      - recipe-app-network

  db:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      - DB_PORT=${DB_PORT}
      - DB_SCHEMA=${DB_SCHEMA}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - recipe-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    container_name: recipe-app-pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    networks:
      - recipe-app-network

  minio:
    image: minio/minio # MinIO Docker image
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_BROWSER_CORS_ALLOW_ORIGIN=${NEXT_PUBLIC_URL}
      - MINIO_API_CORS_ALLOW_ORIGIN=${NEXT_PUBLIC_URL}
    volumes:
      - minio_data:/data
    ports: # MinIO default ports
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - recipe-app-network

  create_buckets:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      # Inject the env variables safely into the container context
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        until (/usr/bin/mc alias set localminio $MINIO_ENDPOINT_URL $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD); do 
          echo 'Waiting for MinIO...'
          sleep 5
        done

        echo "Creating bucket..."
        /usr/bin/mc mb --ignore-existing localminio/$MINIO_BUCKET_NAME

        echo "Setting public download policy..."
        /usr/bin/mc anonymous set download localminio/$MINIO_BUCKET_NAME

        echo 'Bucket initialized successfully!';
        exit 0;
    networks:
      - recipe-app-network

volumes:
  minio_data:
    driver: local
  postgres_data:

networks:
  recipe-app-network:
    driver: "bridge"
